### PR TITLE
Added basic authentication and security

### PR DESCRIPTION
**Pull request by aaronsun1030**

### CODE REVIEW

**Review by karthikRavichandran — COMMENTED** [review]
@DeepaRukminiMahalingappa @Deepika-S1708 Any idea how are we going to integrate this part of Auth in our code?. Any luck in converting our Figma design to Java? If not pl let me know, we don't have much time to get stuck in this work- we can switch to python. Server comp and Modularity can be taken care with python as well. Tantamount of @aaronsun1030 code is present in firebase, @Deepika-S1708 if you want we can explore that. Otherwise, if we want to use this authentication process, @aaronsun1030- you have to create an API and give us the end-point so that I can use it in the existing code.

**Comment by aaronsun1030** [comment]
I think we can convert Figma to HTML/CSS using a [plugin](https://www.figma.com/community/plugin/851183094275736358/figma-to-html) and run a web application using java, with something like this [tutorial](https://www.javatpoint.com/how-to-build-a-web-application-using-java) or [spring](https://spring.io/guides/gs/serving-web-content/). 

Switching to python is a very big change, as we wouldn't even be using our existing Figma UI. It should be a last resort, in my opinion.

**Comment by DeepaRukminiMahalingappa** [comment]
Screenshot 2023-12-01 at 9 55 34 PM

I am unable to convert Figma code into HTML/CSS...Tried with lot of plugins...Also issue in converting .jsx conversion

**Comment by aaronsun1030** [comment]
We are switching to Python from Java, so this code is no longer needed.

**Pull request closed without merging**
